### ISSUE TITLE
go env

### ISSUE THREAD

**Issue by wpsec** [XTeam-Wing/X-AV#2]
windows:ERROR:exec: "bin/go": file does not exist
mac:ERROR:fork/exec bin/go: no such file or directory

<img width="936" alt="image" src="https://user-images.githubusercontent.com/57949806/194203320-5d5bb6ac-e077-4c24-99b1-5fefb8f74360.png">

**Comment by XTeam-Wing** [comment]
之前是在mac下开发的,没测试windows.
调用go编译动态替换后的模板文件
<img width="616" alt="image" src="https://user-images.githubusercontent.com/25416365/194205667-bde728d3-ce22-4a6c-bcb9-fd1e28454537.png">
