### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by wang814** [XTeam-Wing/X-AV#3]

**Comment by 0xAcctracy** [comment]
ERROR:fork/exec bin/go: no such file or directory
RESULT: []
STDERR:

**Comment by Qrayyy** [comment]
怎么解决的

**Comment by XTeam-Wing** [comment]
刚刚翻代码看了下，要设置goroot路径，当时没考虑到windows，主要是自己用。

<img width="817" alt="image" src="https://github.com/XTeam-Wing/X-AV/assets/25416365/980221a0-0c0e-40c1-ae1b-52f972f80c18">
